### ISSUE TITLE
Switch button not clickable when using cache plugin (or possibly ever)

### ISSUE THREAD

**Issue by its-thomas** [Desertsnowman/Caldera-Forms#517] opened 2016-04-01 04:55 UTC
Hi there,

I just noticed that when caching a page using _Comet Cache Pro_ plugin, the Caldera form on the mentioned page, consisting of only switch buttons (German: "Umschalter") is not working anymore, meaning the switch buttons are not clickable. Removing the mentioned page from the caching process "solves" the issue (of course, I would prefer to have the page cached...)

Do you think you could help me out here?

Thanks a lot in advance

Thomas

**Comment by Shelob9** [comment] 2016-04-01 18:25
You should put a cache exception on your page with the form to not cache that page. Caching plugins don't work with dynamic content. You're going to run into lots of issues caching the page with Caldera Forms. The biggest is that the security verification token will stop working.

**Comment by its-thomas** [comment] 2016-04-01 18:31
> You should put a cache exception on your page with the form to not cache that page.

Yes, that's what I did (as stated in my post).

> Caching plugins don't work with dynamic content.

Well, the form worked just the way it was intended to for about 6 months before I noticed it didn't work anymore yesterday....

**Comment by Shelob9** [comment] 2016-04-01 18:33
@its-thomas We have had issues with some caching plugins minifying our already minifed scripts and that causing problems. Does your caching plugin do that?

**Comment by its-thomas** [comment] 2016-04-01 18:41
As stated above, my caching plugin is Comet Cache Pro (see www.cometcache.com / https://wordpress.org/plugins/comet-cache/)

As one of its features, it states:

> JS/CSS Concatenation & Minification
The ability to automatically combine both local & external JS/CSS resources into compressed cache files.

But honestly, Fast Secure Contact Form for example (being another form builder plugin) doesn't seem to have any problems with my caching plugin....

**Comment by Shelob9** [comment] 2016-04-01 19:58
You should try disabling the minfication, our scripts are already minifed.

**Comment by its-thomas** [comment] 2016-04-01 20:59
As far as I can tell, there is no option to disable minification only. So for now, I have disabled caching for the mentioned page...
Still, it was working for before - for a period of multiple months...

**Comment by Shelob9** [comment] 2016-04-01 21:10
@its-thomas I am re-opening this, we will look at toggle switch issues next week.

**Comment by its-thomas** [comment] 2016-04-01 21:18
Thanks! I have just checked again: It's definitely an issue. When caching is enabled, toggle switches cannot be clicked (in order to turn green), although this has been working before.

**Comment by Shelob9** [comment] 2016-04-03 00:24
https://wordpress.org/support/topic/toggle-switch-2

**Comment by its-thomas** [comment] 2016-04-03 08:22
> https://wordpress.org/support/topic/toggle-switch-2

Regarding the support ticket above: My form just as has 6 toggle switches on a singe page / tab - no further pages or tabs.

**Comment by Desertsnowman** [comment] 2016-04-06 07:12
@its-thomas is there a live version where I can see the problem?

**Comment by its-thomas** [comment] 2016-04-06 15:59
@Desertsnowman Stupid question: Do you need a working live version (no caching of page, form works) or a non-working (page cached, form not working)?

**Comment by Desertsnowman** [comment] 2016-04-06 16:23
Non working

**Comment by its-thomas** [comment] 2016-04-06 16:29
@Desertsnowman Voila http://www.adhs-fulda.de/aufmerksamkeitsdefizit-hyperaktivitaet/online-tests/online-test-kinder/

**Comment by Desertsnowman** [comment] 2016-04-06 16:38
ok, and a working one ?

**Comment by its-thomas** [comment] 2016-04-06 16:44
@Desertsnowman http://www.adhs-fulda.de/aufmerksamkeitsdefizit-hyperaktivitaet/online-tests/erwachsene-fragebogen-screening/

**Comment by Desertsnowman** [comment] 2016-04-06 16:52
ok I see.
I'll need to do more tests to find an answer. thanks.

**Comment by its-thomas** [comment] 2016-04-06 16:53
@Desertsnowman Thank YOU! Is it okay if I remove the URLs now?

**Comment by Desertsnowman** [comment] 2016-04-06 16:55
Yup go ahead.

**Comment by Shelob9** [comment] 2016-04-11 19:46
@Desertsnowman Do we have a fix for this yet? I think we should probably do 1.3.4.3 for it if so.

**Comment by Desertsnowman** [comment] 2016-04-12 06:00
@Shelob9 - I found the problem. when a cache plugin combines scripts, they are in a new location. the pollyfill for validation has automatic script inclusion. This is to include as browser needs them. the problem is that the path is relative. so the caching creates new scripts in a cache folder so the scripts that are dynamically included are no longer relative.

I'm working on a solution.

**Closed** 2016-04-12 06:09 UTC
Labels: Blocker For Next Release, bug, bug:major

**Comment by its-thomas** [comment] 2016-04-12 07:14
Great! Thanks so much :-)
