### ISSUE TITLE
Still having css issues after updating to 1.3.2.

### ISSUE THREAD

**Issue by Ribice** [Desertsnowman/Caldera-Forms#398] opened 2016-01-20 07:53 UTC
![image](https://cloud.githubusercontent.com/assets/5403700/12442785/28009f48-bf53-11e5-8d70-89b311fbb339.png)

Spacing before and after dropdown list is different compared to other elements. Same applies for toggle switch.

**Comment by Shelob9** [comment] 2016-01-20 18:02
This is a duplicate of #306

**Closed by Shelob9** 2016-01-20 18:02 UTC
