### ISSUE TITLE
Ajax Submission does not work when form is added to dom via ajax.

### ISSUE THREAD

**Issue by bucketpress** [Desertsnowman/Caldera-Forms#497] opened 2016-03-28 18:27 UTC
I'm displaying Caldera Forms in the following ways:
- loading a page which contains a form via ajax 
- loading a form into dom by using the cf-api endpoint

I've also included wp_enqueue_script( 'cf-dynamic' ). All the assets such as datepickers and css styles are loaded and works properly, when the forms are displayed.

But on Form Submission, the pages reload to an empty page showing only the json code for a successful submission - i.e. ajax submission not working as it should.

**Comment by Desertsnowman** [comment] 2016-03-28 18:29
This exact issue is being addressed in the upcoming release. Have you tried the latest beta version?

**Comment by bucketpress** [comment] 2016-03-29 03:01
Hi David, thanks for this - are you referring to current-dev - 1.3.4-b1?

**Comment by Shelob9** [comment] 2016-03-29 19:48
This isn't the issue that I have been working on, that we have been working on with AJAX submissions. This has to do with loading the form into the DOM via AJAX.

I see several reasons this wouldn't work... Mainly form ID bindings are going to be confused. I'd also worry about conditional loading of the CSS/JS. Getting conditionals setup is going to be the big issue. Have you looked at the way this is handled in connected forms? https://github.com/CalderaWP/cf-connected-forms/blob/master/assets/js/cf-connected-ajax.js

**Comment by Shelob9** [comment] 2016-03-29 19:48
BTW @bucketpress I am closing this, beacuse it's not a bug, it's a usage issue that isn't really a feature, but its doable. Feel free to discuss, but we need to bug garden better.

**Closed by Shelob9** 2016-03-29 19:48 UTC

**Comment by bucketpress** [comment] 2016-04-02 05:29
@Shelob9 , thanks for pointing to to the Connected Forms code. Not too sure, how that specifically since I've not used connected forms yet. But looking the code, seems like the required Form wrapper, and all connected forms and corressponding js were already loaded into dom to begin with. And on 'next/submit' button click, the next form was 'moved' into the display area from its 'hidden' state, 'replacing' the previous form.

If that's the case, then currently the only way to load a CF form via ajax, would be to first load it normally in the dom, and then hide it, so that corresponding js that binds to the form are loaded. The form that I'll loading is loaded together with a ajax loaded post, because I've specified the form to have some default values such such post title and post url. That means 
- the initially normal-loaded form will have the correct js bindings but not the correct input default values I need.
- the ajax-loaded form will not have correct js bindings, but will have the required input default values.

So after ajax-loading the form, I'll have to implement the next steps:
- Replace the normal-loaded form's input with the ajax-loaded form's values
- Then remove the ajax-loaded form from DOM, and 'move' the normal-loaded form that now has the correct input values, with required js bindings into place.
