### ISSUE TITLE
Rows

### ISSUE THREAD

**Issue by paaljoachim** [Desertsnowman/Caldera-Forms#219] opened 2015-08-26 21:13 UTC
Layout Builder

Click on a field element in a row activates the field.
Outside the move cursor is active.

Empty row one can only drag with the top right icon. Non empty row one can drag multiple places.

Delete row is easy enough click the top left x icon to delete the row.
Fields could also on the left have an x to delete the field.

**Comment by paaljoachim** [comment] 2015-08-29 23:03
<b>Duplicating content and row</b>. Instead of having to Add Element 3 times in a row to create a First and Last name and title field what about holding down shift and dragging the row to another row. Doing so duplicates the row and content. Perhaps even having a duplicate icon next to the drag row icon.

**Comment by paaljoachim** [comment] 2015-08-29 23:04
Drag content to non existing row (drag to the + sign) automatically creates a new row with the content.

**Comment by paaljoachim** [comment] 2015-08-29 23:09
Update Form alerts about rows that do not contain content. Hover the mouse over them and the pencil icon shows up. Here one could also have a trash can on the left side of the content box. Choosing to either click the pencil to do something with the content or clicking the trash icon to delete the field.

**Comment by Desertsnowman** [comment] 2015-08-30 10:37
just a note @paaljoachim - I don't comment much on your posts, but I really appreciate the time you take in analyzing the UI and giving feedback on how to improve. this is truly the best support anyone can give. Thanks!

**Comment by paaljoachim** [comment] 2015-08-30 11:17
Thanks David I really appreciate your note!
I will continue to brain storm on my experiences and add them in and count on whenever something needs to be discussed it will be.

**Comment by dlincoln** [comment] 2015-08-30 15:19
+1 @paaljoachim! Duplicating both elements and rows would be a HUGE improvement for CF's main function (quickly prototyping forms and basic functions). The lack of this can be a big pita on long forms... 

for instance I have a rate-generator form with a dozen different rate-types, each containing 2-4 variables. In almost all cases the rows are similar to other rows; I could have built just 3 rows with the same conditions (if selected type != this row's name, hide and disable require), and duped them 3-4 times each and called it a day.

In general it's useful to copy WP's norms. Columns of items and blocks frequently have the option to duplicate, trash or edit. This isn't exactly a column of course, but this feature would be recognized and used by WP savvy designers out of the box, without documentation.

**Comment by Shelob9** [comment] 2015-12-11 02:01
This is a duplicate of several issues.

**Closed by Shelob9** 2015-12-11 02:01 UTC
Labels: enhancement
