### ISSUE TITLE
Dynamic Image in HTML mailer

### ISSUE THREAD

**Issue by seanvfs** [Desertsnowman/Caldera-Forms#507] opened 2016-03-30 19:33 UTC
I'm having an issue getting a dynamic image into the html mailer. I'm trying to use a filter to grab the url of a WooCommerce product image and put it in the Caldera mailer. I've got the post id of the product image using a hidden field with the default value set as "{post_meta:_thumbnail_id}". From there I planned on using a filter to do a db query to grab the image.

The issue is that i couldn't find the right filter to run my logic on. So I gave up on this and decided to use a regular text field, hide it via css and use jquery to update it's value with the image url. This works and saves with the other entry data properly.

Now I'm facing an issue with the email being sent without an image tag in it at all. Is there something I'm missing with the magic tags logic filtering out images?

**Comment by Shelob9** [comment] 2016-03-30 21:21
Magic tags rendering will not exclude image tags, but if I understand you're just passing the ID of the image, that's not going to work. You will need to add your own magic tag to render the image using the caldera_forms_do_magic_tag filter.

I am closing this as it is a usage issue, not a bug.

Feel free to submit a support request at https://calderawp.com/support if you need help working with that filter.

**Closed by Shelob9** 2016-03-30 21:21 UTC

**Comment by seanvfs** [comment] 2016-03-30 22:14
Josh,

Sorry if I was unclear.  I wanted to give a bit of background as to what I had hoped to do. 

I'm currently using jQuery to set a css-hidden text input in a form and output that text field in the mailer as an image tag using %field_name% in the src attribute.  What i end up with is the proper url saved in the "entries" area and a delivered html email that has had the entire img tag removed.

I tried to submit a support ticket but the calderawp site won't allow a submission without being logged in and having a "purchased" product in my account to auto-fill a form field.  It's a bit counter-intuitive when the plugin is freely available on the WordPress Plugin Repository.  If I'm missing something about this please let me know.
