### ISSUE TITLE
Page Unresponsive on the admin end

### ISSUE THREAD

**Issue by Ginno89** [Desertsnowman/Caldera-Forms#485] opened 2016-03-22 07:38 UTC
Hello,
I really like your plugin but I have on concern. Each time I try to access it in the back end wordpress admin I get the error message page unresponsive. I tried switching from chrome to firefox and I got an error to do with a script. I am not a programmer by the way. So please describe your solution in lay man's terms. I would like to buy your add ons but before that I need to make sure that your plug in works properly and will not crash on me
![caldera form problem](https://cloud.githubusercontent.com/assets/18001035/13944724/4948ef7a-efcd-11e5-8ecc-e992404df12d.jpg)
![caldera forms scripting error](https://cloud.githubusercontent.com/assets/18001035/13944882/a6c43000-efce-11e5-8e35-8f9f1231d732.jpg)

**Comment by Shelob9** [comment] 2016-03-23 23:25
Probably a dupe of #461 

@Ginno89  Most likely this means that there is a PHP error somewhere that is breaking our admin interface, but those can be hard to see. Can you please try again with debug logging active? See: https://www.elegantthemes.com/blog/tips-tricks/using-the-wordpress-debug-log If you can log some errors while reproducing this, it would help us find the source of the error.

Also, have you tried with all other plugins disabled as well as with the default theme active?

**Comment by Shelob9** [comment] 2016-04-05 05:36
Closing this as we have not heard back in almost 2 weeks and can not reproduce.

**Closed by Shelob9** 2016-04-05 05:36 UTC
