### ISSUE TITLE
Invalid email breaks 'success message' screen

### ISSUE THREAD

**Issue by digitalsmithy** [Desertsnowman/Caldera-Forms#448] opened 2016-03-05 00:49 UTC
I see from other posts your having 'bug fun' - This plugin is a fantastic bit of kit - if that's any consolation...Thanks for your efforts.

Another submission bug I'm afraid.

If you enter e@e (or similar short/invalid email) on (a / my?) form, the 'success message' crashes. Goes to a blank screen with something like this on it.

`{"result":"Thanks for asking Mike Jones!\nWe'll get back to you shortly.","data":{"cf_id":"22"},"html":"<div class=\" alert alert-success\">Thanks for asking Mike Jones!\nWe'll get back to you shortly.<\/div>","type":"complete","form_id":"CF56c77c0b41994","form_name":"Can we help you?","status":"complete"}`

The email to admin sends ok, so the 'process' is completing. If you refresh the 'blank page with code' page the form submits again. At a guess, the "e@e" is mistakenly being parsed into the code? (I'm no programmer, just guessing). If you enter a genuine email, the form submits ok.

I get that this is 'obscure' but users will be users, and some *^&% is bound to misstype or enter garbage for no reason, and it will crash the site.

Good luck :)

**Comment by digitalsmithy** [comment] 2016-03-05 00:52
Sorry - just to clarify.

I can enter edward@bernard
in the email and it crashes the form

but edward@bernard.co.uk
submits ok (all other details on form identical.)

If that helps.

**Comment by Shelob9** [comment] 2016-03-22 00:36
Closing beacuse #483 is the root cause and is about to be fixed #483

**Closed by Shelob9** 2016-03-22 00:36 UTC
