### ISSUE TITLE
If multiple files are attached, submission does not save.

### ISSUE THREAD

**Issue by williamjwallace** [Desertsnowman/Caldera-Forms#446] opened 2016-03-04 16:15 UTC
tried on chrome and i.e. and any changes made to the form will not save.

I've dumped browser cache on both and still won't save changes.

**Comment by Desertsnowman** [comment] 2016-03-04 16:18
strange. nothing changed in admin at all for this version. do you have any javascript errors?

**Comment by williamjwallace** [comment] 2016-03-04 16:20
no errors, but I did notice that there used to be a little popup that says "form now saved" (or something similar) used to come up over the save button after you clicked it, but now that does not happen. All I see is the circle go around then disappear.

**Comment by williamjwallace** [comment] 2016-03-04 16:22
I've changed the mailer settings and the form itself and no saves for both after clicking save.

**Comment by williamjwallace** [comment] 2016-03-04 16:24
Sorry it was a drop down over the button that said "updated successfully" that no longer takes place.

**Comment by Desertsnowman** [comment] 2016-03-04 16:25
Can you try create a new form then click save and see if that works?

**Comment by williamjwallace** [comment] 2016-03-04 16:31
Save works on new forms but not existing forms.

I even tried to add a new field to the old form and got no "updated successfully" alert. just the spinning ball.

**Comment by Desertsnowman** [comment] 2016-03-04 16:33
can you export the form that wont save and send it to me? david@calderawp.com

**Comment by williamjwallace** [comment] 2016-03-04 16:35
how would you like the export? the backup (json) file or PHP include file?

**Comment by Desertsnowman** [comment] 2016-03-04 16:37
json will be fine

**Comment by williamjwallace** [comment] 2016-03-04 16:39
on it's way

**Comment by Desertsnowman** [comment] 2016-03-04 16:50
thanks got it. I'll need some time to investigate. Can you look at the conditions tab and see if they have gone missing?

**Comment by williamjwallace** [comment] 2016-03-04 16:51
yes, conditions are missing.

**Comment by williamjwallace** [comment] 2016-03-04 16:53
OK, weird.....

I added the condition back to my form and now it says "saved successfully" when saving.

**Comment by Desertsnowman** [comment] 2016-03-04 16:53
SIGH! thanks. there is something in there thats causing it to die. 
and thank you for the export. I can reproduce the problem which helps a lot. I can now try figure out whats causing it and fix it.

**Comment by Desertsnowman** [comment] 2016-03-04 16:54
I got a report a while back that conditions died and could never reproduce it. so this really helps.

**Comment by williamjwallace** [comment] 2016-03-04 16:55
ok false alarm on that one.

I just went back in and now the condition is missing. *grumble*

**Comment by Desertsnowman** [comment] 2016-03-04 16:55
yup somethings not happy. I'm so sorry. I'll try find the bug asap.

**Comment by williamjwallace** [comment] 2016-03-04 16:58
yup, tried to save again and after save the condition went missing again.

I'm sooooo glad I'm not a programmer/developer I do'nt have that kind of patience!

but hey, fix this and if you're ever in Vegas I'll hook you up on one of our Party Tours!!! lol

**Comment by Desertsnowman** [comment] 2016-03-04 17:00
lol, I don't have the patience either. I'm just a sucker for punishment. 
And thanks, doubt I'll ever be that side of the world anytime soon. It's not an easy trip from south africa.

**Comment by williamjwallace** [comment] 2016-03-04 17:01
well crap, ya that is kind of a long ass trip ins't it?

**Comment by Desertsnowman** [comment] 2016-03-04 17:03
indeed it is! anyway, I'll get this sorted out. I'm going to need to take apart the export line by line to see which line it breaks at then find out why and fix it. it may take a day or two. maybe 12.

**Comment by Shelob9** [comment] 2016-03-04 17:20
Can you please be more descriptive of your issue?

Are you talking about in the form editor or front-end form submissions?
Nothing changed in the admin side from 1.3.3 to 1.3.3.1, only in the
front-end...

Can you please provide us with any console errors you are seeing as well as
what version of WordPress you are using.

**Comment by Desertsnowman** [comment] 2016-03-04 17:34
@Shelob9 - this is something I picked up a few weeks back but couldn't replicate it. this however helps. there is no console errors. it just breaks. I'm investigating.

**Comment by williamjwallace** [comment] 2016-03-04 17:43
Saving in the Form Editor.

using WP 4.3.3

**Comment by dchacons** [comment] 2016-03-07 16:33
Does this update will fix: Only one attachment of a multi-select image field gets attached to mailer #429 ?

Thanks

**Comment by williamjwallace** [comment] 2016-03-09 18:50
Hi David, Any news on a fix for this issue yet?

**Comment by Shelob9** [comment] 2016-03-13 20:57
I reproduced and fixed the issue where multiple files could not be ATTACHED. But I can't reproduce the issue where multiple file fields can't be saved. Maybe it was related to verification issues in 1.3.3/1.3.2 Need some way to reproduce this to fix it...

**Comment by Shelob9** [comment] 2016-03-13 21:22
If you can reproduce this issue with CF 1.3.3, please try latest beta (https://calderawp.com/cf-latest-beta) and see if it's still there. If it's fixed let us know here. If not, help me reproduce this so I can fix it: DM me on twitter @Josh412, WordPress.org Slack Shelob9 or email me Josh@CalderaWP.com

**Comment by Shelob9** [comment] 2016-03-17 21:20
I FOUND OUT HOW TO REPRODUCE THIS!
File field must be not-required, multiple files allowed and set to attach to mailer.

![screen shot 2016-03-17 at 5 19 06 pm](https://cloud.githubusercontent.com/assets/1994311/13861612/9a38d7cc-ec64-11e5-83b4-1efbdfacd6e4.png)

**Comment by williamjwallace** [comment] 2016-03-17 21:25
That would be great but I'm not having trouble submitting files, only saving the form after a change is made from the last update of Caldera.

As you can see in the above posts I can only save the form "AFTER" I have re-added the condition (all conditions dropped off the form after the Caldera update) to the form, which is unacceptable.

**Comment by Shelob9** [comment] 2016-03-17 21:28
@williamjwallace Probably related -- same error: nothing being uploaded -- I think I've got a fix for what's breaking original submission, once I have that in, we can look at your issue.

**Comment by williamjwallace** [comment] 2016-03-17 21:30
Side note to my above note:

Once a condition is added and the form is saved, the conditions are again not visible or have been magically removed. So it's a chase my tail sort of thing.

**Comment by Shelob9** [comment] 2016-03-17 21:41
`Once a condition is added and the form is saved, the conditions are again not visible or have been magically removed. So it's a chase my tail sort of thing.` This sounds like a separate issue. And it is known, when @Desertsnowman gets back from his vacation, I am going to have him look at that.

That is if he's not killed by hyenas... https://twitter.com/dcramer/status/710548084800032769

**Comment by Shelob9** [comment] 2016-03-17 21:47
@williamjwallace With 231f8a4 I can now submit the form and edit it without adding files.

I opened #474 to deal with the fact that editing causes the files to be lost.

**Comment by Shelob9** [comment] 2016-03-17 21:47
Closing via 231f8a4

**Closed by Shelob9** 2016-03-17 21:47 UTC
Labels: Blocker For Next Release, bug:major, This is what I get for trying to invent stuff.

**Comment by Shelob9** [comment] 2016-03-17 22:06
@williamjwallace If you can pull the latest beta now via Github or get the zip with https://CalderaWP.com/cf-latest-beta and test, the file upload issues should be fixed. Please let me know if this checks out for you.
