### ISSUE TITLE
Caldera Forms 1.3.3.1 freeze/ become uneditable

### ISSUE THREAD

**Issue by RBourry** [Desertsnowman/Caldera-Forms#479] opened 2016-03-21 16:46 UTC
Hey there,
I have built a new contact form with CF yesterday and today when I wanted to go on editing the form, it just didn't respond anymore. When I e.g. click on the tab Conditions, I can see that the URL changes to #conditions-config-panel but I still see the Layout panel which is frozen. I have already tried deactivating all other Plugins, but nothing seems to fix it. 
There is another form on my site which was generated by another user earlier and that one is still editable.
My Form uses an alternative datepicker which I coded in an html field, that's the only difference I can detect between the two forms.
Generally I use Caldera Custom Fields, and Verify Email for Caldera Forms additionally to the builder.
My Wordpress version is 4.4.2
My Caldera Forms version is 1.3.3.1
My PHP Version is 5.6.16
And the MySQL is 5.5.47

**Comment by Shelob9** [comment] 2016-03-21 17:10
Did you test with out the add-ons active and with your "alternative datepicker" disabled? Wondering if something in the UI is making an error and therefore you are seeing #461

Do you have any console errors? Is WP_DEBUG enabled?

**Comment by RBourry** [comment] 2016-03-21 18:24
I did test it without any other addons activated but the caldera forms addon. But it didn't work.
I can't remove my alternative datepicker because I can't edit the form anymore. As far as I know this happens as soon as an html field is added to the form. I created another form which had a selfbuilt IBAN validator and that form had the same problem and became ineditable.
I did not get any error message of any kind. Don't know if debug is enabled, because I don't have access to our main server, only to the wordpress-surface.

**Comment by Shelob9** [comment] 2016-03-22 01:04
Here is the thing, in the Caldera Forms admin, when it loads a partial file and that partial prints an error, it breaks our templating system. The error isn't normally visible. This is issue #461 

 So one of your custom fields is probably causing an error. We can rule that out or confirm it by deactivating the plugins that add those. Also, you should see if you can capture those errors using debug logging (https://deliciousbrains.com/why-use-wp-debug-log-wordpress-development/)

**Comment by Shelob9** [comment] 2016-03-23 23:22
@RBourry I am closing this as a dupe of #461 -- if you have additional details to show it is a different issue, please re-open.

**Closed by Shelob9** 2016-03-23 23:22 UTC
Labels: bug
