### ISSUE TITLE
Add element button

### ISSUE THREAD

**Issue by islanddesign** [Desertsnowman/Caldera-Forms#356] opened 2015-11-19 21:11 UTC
Getting a strange break in the UI in both Chrome and Firefox - The add element button is broken, it has lost it's blue background color, is split in two
![caldera_chrome](https://cloud.githubusercontent.com/assets/5226629/11284493/24f5697e-8ed8-11e5-83db-cbbb8629a2db.png)
![caldera_firefox2](https://cloud.githubusercontent.com/assets/5226629/11284495/27812b06-8ed8-11e5-85de-002d79efa639.png)

**Comment by Shelob9** [comment] 2015-11-19 22:11
@islanddesign Thanks for the report? What OS are you using? Also, what happens if you disable all other plugins? I'm not seeing this issue on my test sites. Another plugin or theme may be loading conflicting styles in our admin screen that are affecting how our admin renders.

**Comment by islanddesign** [comment] 2015-11-20 21:47
Hi @Shelob9 

I disabled all the other plugins and one-by-on activated them and guess what? All is well wit the "Add Element" button! (on both Chrome and Firefox)

I'm on a Mac... running latest version of Wordpress with the Dvi theme from Elegantthemes

Thanks for your time

**Comment by Shelob9** [comment] 2016-04-10 21:16
I can't reproduce with latest Divi + Caldera Forms. Closing.

**Closed by Shelob9** 2016-04-10 21:16 UTC
Labels: Conflict
