### ISSUE TITLE
Select2 ( Multiselect ) not storing in the db

### ISSUE THREAD

**Issue by gdarko** [Desertsnowman/Caldera-Forms#536] opened 2016-04-08 15:39 UTC
Hello,

First, you plugin is kickass! I really like it, i read your support on WordPress and decided to write here about the issue.

Currently we decided to use a multiple selection field which we autopopulate with post type title & id, but when someone send a message they are not stored or sent, just the label stays empty.

Is it something up to the configuration or this is definitely a bug i am not sure.

Keep up the good work!

Best Regards,
Darko

**Comment by Shelob9** [comment] 2016-04-08 18:29
@gdarko I'm glad you are loving Caldera Forms. Thanks for reporting this bug. It has actually been reported already. I am closing this issue as a duplicate of #400 just to keep things tidy, not beacuse we don't intend to fix it. Please follow #400 for updates.

**Closed by Shelob9** 2016-04-08 18:29 UTC
