### ISSUE TITLE
Entrie export: Warning: Illegal string offset 

### ISSUE THREAD

**Issue by wolfvanhaeren** [Desertsnowman/Caldera-Forms#533] opened 2016-04-07 06:41 UTC
Hello,
It seems not possible to view or export entries since the last update.
I have this issue on multiple sites.
When I view an entry it stays blank. If I click export I get:
Warning: Illegal string offset 'opt1870583' in /usr/home/lsw_data_02_dro/*******/www/a/wp-content/plugins/caldera-forms/classes/core.php on line 4037

over and over again.

What should I do?

**Comment by Shelob9** [comment] 2016-04-08 00:09
This is a duplicate of #508 which is already fixed. Please pull the current-dev branch or download the zip for that branch to get the fix.

**Closed by Shelob9** 2016-04-08 00:09 UTC

**Comment by wolfvanhaeren** [comment] 2016-04-11 06:47
I am now using the current stable build 1.3.4.2. but I still have this problem.

**Comment by Shelob9** [comment] 2016-04-11 08:15
It is fixed in the current-dev branch. We only merge to current-stable when a release is ready.

Pull current-dev to get the fix.

**Comment by wolfvanhaeren** [comment] 2016-04-11 08:24
Thanks it works now!
