### ISSUE TITLE
Can't save multiple entries from select2 fields in db

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#400] opened 2016-01-20 22:02 UTC

**Comment by paulbakker-gh** [comment] 2016-01-20 22:04
Thanks for picking this up so quickly !

**Comment by dnusca** [comment] 2016-02-25 15:30
Need some hands on this?

**Comment by Shelob9** [comment] 2016-02-25 20:41
@dnusca If you have a fix, that would be awesome. Be sure to put the pull request in against the current-dev branch.

**Comment by dnusca** [comment] 2016-02-29 10:25
@Shelob9 I have a quick fix. It appears that the because the chosen options from the multiselect are stored in array indexed from 0 they do not match with the option id's stored in the field config.

I've linked a fix for this however I don't think this is a suitable solution.

A better solution may be to index the option array in the field config from 0 rather than the custom indexes based on the option values? I'm not too familiar with the structure, so perhaps you could advise?

https://github.com/dnusca/Caldera-Forms/commit/e556a3743dc9f56c4af50a5bfca0cc4bc856d1b2

**Comment by Shelob9** [comment] 2016-04-05 05:39
Pretty sure this is now fixed. I will retest.

**Comment by paulbakker-gh** [comment] 2016-04-20 15:34
I don't understand, you've modified this to milestone 1.3.6 but it has been fixed ?

**Comment by Desertsnowman** [comment] 2016-04-20 15:44
Sorry I mistakenly labeled it that.  Was meant to be set as a duplicate of issue #274

**Comment by paulbakker-gh** [comment] 2016-04-20 16:30
Can happen !

What really decides consumers to buy or not to buy is the content of your advertising, not its form - David Ogilvy

**Comment by Desertsnowman** [comment] 2016-04-20 17:29
Good thing it free then 😉

**Comment by Desertsnowman** [comment] 2016-04-20 17:32
closed via #274

**Closed by Desertsnowman** 2016-04-20 17:32 UTC
Labels: bug, Puntable
